lib/movies_web/router.ex
defmodule MoviesWeb.Router do
  use MoviesWeb, :router
  use Pow.Phoenix.Router
  # alias MoviesWeb.Router.Helpers, as: Routes

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {MoviesWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MoviesWeb.Plugs.SetCurrentUser
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", MoviesWeb do
    pipe_through [:browser]

    get "/search", SearchController, :index
    resources "/", MovieController, only: [:index, :show]
  end

  scope "/movies", MoviesWeb do
    pipe_through [:browser]

    get "/watch_later/:id", MovieController, :watch_later
    get "/remove_watchlist/:id", MovieController, :remove_watchlist
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/movies/application.ex
defmodule Movies.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  @impl true
  def start(_type, _args) do
    children = [
      # Start the Ecto repository
      Movies.Repo,
      # Start the Telemetry supervisor
      MoviesWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Movies.PubSub},
      # Start the Endpoint (http/https)
      MoviesWeb.Endpoint
      # Start a worker by calling: Movies.Worker.start_link(arg)
      # {Movies.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Movies.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  @impl true
  def config_change(changed, _new, removed) do
    MoviesWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/movies/mailer.ex
defmodule Movies.Mailer do
  use Swoosh.Mailer, otp_app: :movies
end

lib/movies/repo.ex
defmodule Movies.Repo do
  use Ecto.Repo,
    otp_app: :movies,
    adapter: Ecto.Adapters.Postgres
end

lib/movies/users/user.ex
defmodule Movies.Users.User do
  use Ecto.Schema
  use Pow.Ecto.Schema
  alias Movies.Watchlist.Movie

  schema "users" do
    pow_user_fields()

    many_to_many(
      :movies,
      Movie,
      join_through: "user_movie",
      on_replace: :delete
    )

    timestamps()
  end
end

lib/movies/watchlist.ex
defmodule Movies.Watchlist do
  @moduledoc """
  The Watchlist context.
  """

  import Ecto.Query, warn: false
  alias Ecto.Changeset
  alias Movies.Repo

  alias Movies.Watchlist.{Movie, UserMovie}
  alias MoviesWeb.MovieService

  def list_movies(user) do
    user = user |> Repo.preload(:movies)
    user.movies
  end

  @spec get_movie!(any) :: false | nil | true | binary | list | number | map
  def get_movie!(id), do: MovieService.get(id)

  def create_movie(attrs \\ %{}) do
    %Movie{}
    |> Movie.changeset(attrs)
    |> Repo.insert()
  end

  def search(movie_name) when is_binary(movie_name) do
    MovieService.search(movie_name)
  end

  def search(_), do: "Not a valid movie name"

  def watch_movie(user, movie_id) do
    user_movie = find_or_insert(movie_id)
    user_loaded = Repo.preload(user, [:movies])

    user_loaded
    |> Changeset.change()
    |> Changeset.put_assoc(:movies, [user_movie | user_loaded.movies])
    |> Repo.update!()
  end

  def remove(user, movie_id) do
    Repo.delete_all(user_movie_query(user.id, movie_id))
  end

  defp find_or_insert(movie_id) do
    {movie_id, ""} = Integer.parse(movie_id)
    required_movie = get!(movie_id)

    if required_movie do
      required_movie
    else
      {:ok, movie} = create_movie(%{movie_id: movie_id})
      movie
    end
  end

  defp get!(movie_id) do
    Movie |> Repo.get_by(movie_id: movie_id)
  end

  defp user_movie_query(user_id, movie_id) do
    from(um in UserMovie,
      where: um.user_id == ^user_id,
      where: um.movie_id == ^movie_id
    )
  end
end

lib/movies/watchlist/movie.ex
defmodule Movies.Watchlist.Movie do
  use Ecto.Schema
  import Ecto.Changeset
  alias Movies.Users.User

  schema "movies" do
    field :movie_id, :integer

    many_to_many(
      :users,
      User,
      join_through: "user_movie",
      on_replace: :delete
    )

    timestamps()
  end

  @doc false
  def changeset(movie, attrs) do
    movie
    |> cast(attrs, [:movie_id])
    |> validate_required([:movie_id])
  end
end

lib/movies/watchlist/user_movie.ex
defmodule Movies.Watchlist.UserMovie do
  @moduledoc """
    UserMovie module
  """

  use Ecto.Schema
  import Ecto.Changeset

  alias Movies.Users.User
  alias Movies.Watchlist.Movie

  @primary_key false
  schema "user_movie" do
    belongs_to(:user, User, primary_key: true)
    belongs_to(:movie, Movie, primary_key: true)
  end

  @required_fields ~w(user_id movie_id)a
  def changeset(user_movie, params \\ %{}) do
    user_movie
    |> cast(params, @required_fields)
    |> validate_required(@required_fields)
    |> foreign_key_constraint(:user_id)
    |> foreign_key_constraint(:movie_id)
    |> unique_constraint([:user, :movie],
      name: :user_id_movie_id_unique_index,
      message: "Already exists"
    )
  end
end

lib/movies_web/controllers/current_user_controller.ex
defmodule MoviesWeb.CurrentUserController do
  defmacro __using__(_) do
    quote do
      def action(conn, _) do
        args = [conn, conn.params, conn.assigns.current_user]
        apply(__MODULE__, action_name(conn), args)
      end
    end
  end
end

lib/movies_web/controllers/movie_controller.ex
defmodule MoviesWeb.MovieController do
  use MoviesWeb, :controller

  alias Movies.Watchlist
  alias Movies.Users.User
  plug MoviesWeb.Plugs.AuthenticateUser

  use MoviesWeb.CurrentUserController

  def index(conn, _params, current_user) do
    movies = Watchlist.list_movies(current_user)
    render(conn, "index.html", movies: movies)
  end

  def show(conn, %{"id" => id}, _current_user) do
    movie = Watchlist.get_movie!(id)
    render(conn, "show.html", movie: movie)
  end

  def watch_later(conn, %{"id" => id}, current_user) do
    case Watchlist.watch_movie(current_user, id) do
      %User{} -> redirect_info(conn, :info, "Movie added to watchlist")
      {:error, _} -> redirect_info(conn, :error, "Something went wrong, please try again")
    end
  end

  def remove_watchlist(conn, %{"id" => id}, current_user) do
    case Watchlist.remove(current_user, id) do
      {1, nil} ->
        redirect_info(conn, :info, "Movie removed from watchlist")

      {0, nil} ->
        redirect_info(conn, :error, "Moview not found in watchlist")
    end
  end

  defp redirect_info(conn, type, message) do
    conn
    |> put_flash(type, message)
    |> redirect(to: Routes.movie_path(conn, :index))
  end
end

lib/movies_web/controllers/search_controller.ex
defmodule MoviesWeb.SearchController do
  use MoviesWeb, :controller
  alias Movies.Watchlist

  plug MoviesWeb.Plugs.AuthenticateUser when action in [:index]
  use MoviesWeb.CurrentUserController

  def index(conn, _params, current_user) do
    query_param = conn.query_params["query"]
    response = Watchlist.search(query_param)
    results = response["results"]

    render(conn, "index.html",
      query: query_param,
      results: results,
      current_user: current_user
    )
  end
end

lib/movies_web/views/error_view.ex
defmodule MoviesWeb.ErrorView do
  use MoviesWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/movies_web/views/layout_view.ex
defmodule MoviesWeb.LayoutView do
  use MoviesWeb, :view

  # Phoenix LiveDashboard is available only in development by default,
  # so we instruct Elixir to not warn if the dashboard route is missing.
  @compile {:no_warn_undefined, {Routes, :live_dashboard_path, 2}}
end

lib/movies_web/views/movie_view.ex
defmodule MoviesWeb.MovieView do
  use MoviesWeb, :view
  alias MoviesWeb.MovieService

  def adult_content(adult) do
    if adult, do: "Yes", else: "No"
  end

  def user_movie(%{movie_id: movie_id}) do
    MovieService.get(movie_id)["title"]
  end
end

lib/movies_web/views/search_view.ex
defmodule MoviesWeb.SearchView do
  use MoviesWeb, :view
end

lib/movies_web/templates/layout/app.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
  <%= @inner_content %>
</main>

lib/movies_web/templates/layout/live.html.heex
<main class="container">
  <p class="alert alert-info" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="info"><%= live_flash(@flash, :info) %></p>

  <p class="alert alert-danger" role="alert"
    phx-click="lv:clear-flash"
    phx-value-key="error"><%= live_flash(@flash, :error) %></p>

  <%= @inner_content %>
</main>

lib/movies_web/templates/layout/root.html.heex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="csrf-token" content={csrf_token_value()}>
    <%= live_title_tag assigns[:page_title] || "Movies", suffix: " · Phoenix Framework" %>
    <link phx-track-static rel="stylesheet" href={Routes.static_path(@conn, "/assets/app.css")}/>
    <script defer phx-track-static type="text/javascript" src={Routes.static_path(@conn, "/assets/app.js")}></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav>
          <ul>
            <%= if @current_user do %>
              <li><%= @current_user.email %></li>
              <li><%= link "Sign out", to: Routes.pow_session_path(@conn, :delete), method: :delete %></li>
            <% else %>
              <li><%= link "Register", to: Routes.pow_registration_path(@conn, :new) %></li>
              <li><%= link "Sign in", to: Routes.pow_session_path(@conn, :new) %></li>
            <% end %>
          </ul>
        </nav>
        <h1> Trending Movies </h1>
        <%= if @current_user do %>
          <nav>
            <%= form_for @conn, Routes.search_path(@conn, :index), [method: :get, class: "search-box"], fn f -> %>
              <%= text_input f, :query %>
              <%= submit "Search" %>
            <% end %>
          </nav>
        <% end %>
      </section>
    </header>
    <%= @inner_content %>
  </body>
</html>

lib/movies_web/templates/movie/edit.html.heex
<h1>Edit Movie</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.movie_path(@conn, :update, @movie)) %>

<span><%= link "Back", to: Routes.movie_path(@conn, :index) %></span>

lib/movies_web/templates/movie/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :movie_id %>
  <%= number_input f, :movie_id %>
  <%= error_tag f, :movie_id %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/movies_web/templates/movie/index.html.heex
<h1>My Watchlist</h1>

<table>
  <tbody>
    <%= if length(@movies) > 0 do %>
      <%= for movie <- @movies do %>
        <%= render "movie.html", conn: @conn, movie: movie %>
      <% end %>
    <% else %>
          <h2> No movies foud in the watchlist </h2>
    <% end %>
  </tbody>
</table>

lib/movies_web/templates/movie/movie.html.heex
<tr>
    <td><%= link user_movie(@movie), to: Routes.movie_path(@conn, :show, @movie.movie_id) %></td>

    <td>
        <span><%= link "Remove", to: Routes.movie_path(@conn, :remove_watchlist, @movie) %></span>
    </td>
</tr>

lib/movies_web/templates/movie/new.html.heex
<h1>New Movie</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.movie_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.movie_path(@conn, :index) %></span>

lib/movies_web/templates/movie/show.html.heex
<h1>Show Movie</h1>

<ul>
  <strong>Movie</strong>
  <h2 class="movie_title"><%= @movie["title"] %></h2>
  <li><strong>Origninal Language:</strong> <%= @movie["original_language"] %></li>
  <li><strong>Overview:</strong> <%= @movie["overview"] %></li>
  <li><strong>Popularity:</strong> <%= @movie["popularity"] %></li>
  <li><strong>Release Date:</strong> <%= @movie["release_date"] %></li>
  <li><strong>Poster Path:</strong> <%= @movie["poster_path"] %></li>
  <li><strong>Adult:</strong> <%= adult_content(@movie["adult"]) %></li>
  <li><strong>Vote Average:</strong> <%= @movie["vote_average"] %></li>
</ul>



<span><%= link "Watch Later", to: Routes.movie_path(@conn, :watch_later, @movie["id"]), class: "watch_later" %></span>
| <span><%= link "Back", to: Routes.movie_path(@conn, :index) %></span>

lib/movies_web/templates/search/index.html.eex
<h1>Search results for <%= @query %></h1>

<table>
  <thead>
    <tr>
      <th>Movies</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for result <- @results do %>
    <%= render "search_result.html", conn: @conn, result: result %>
<% end %>
  </tbody>
</table>

lib/movies_web/templates/search/index.html.heex
<h1>Search results for <%= @query %></h1>

<table>
  <thead>
    <tr>
      <th>Movies</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
    <%= for result <- @results do %>
        <%= render "search_result.html", conn: @conn, result: result, current_user: @current_user %>
    <% end %>
  </tbody>
</table>

lib/movies_web/templates/search/search_result.html.heex
<tr>
    <td><%= link @result["title"], to: Routes.movie_path(@conn, :show, @result["id"]) %></td>
    
    <td>
        <span><%= link "Watch Later", to: Routes.movie_path(@conn, :watch_later, @result["id"]), class: "watch_later" %></span>
    </td>
</tr>